{{- if or .Values.configmap.create .Values.pod.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- if .Values.pod.env }}
  name: {{ include "monochart.name" . }}-env
  {{- else }}
  name: {{ .Values.configmap.name | default (include "monochart.name" .) }}
  {{- end }}
data:
  {{- with .Values.configmap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.pod.env }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
