{{- if .Values.externalSecretsIo.create }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecretsIo.name }}-external-secret
  labels:
    {{- include "monochart.labels" . | nindent 4 }}
    {{- with .Values.externalSecretsIo.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecretsIo.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecretsIo.clusterSecretStoreRef }}
  target:
    name: {{ .Values.externalSecretsIo.name }}
    creationPolicy: {{ .Values.externalSecretsIo.creationPolicy }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecretsIo.ssmSecretKey }}
{{- end }}
