{{- if or .Values.pod.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monochart.name" . }}-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "monochart.registrySecret" . }}
{{- end }}
