{{- if .Values.imagePullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name | default (include "monochart.name" .)}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "monochart.registrySecret" . }}
{{- end }}
