{{- if .Values.imagePullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monochart.name" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "monochart.registrySecret" . }}
{{- end }}
