{{- if .Values.job.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "monochart.name" . }}
  {{- with .Values.job.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "monochart.labels" . | nindent 4 }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    metadata:
      {{- with .Values.job.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "monochart.labels" . | nindent 8 }}
        {{- with .Values.job.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      {{- with .Values.pod.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "monochart.name" . }}
          {{- with .Values.pod.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ .Values.pod.image }}
          imagePullPolicy: {{ .Values.pod.imagePullPolicy }}
          {{- if .Values.pod.command.override }}
          {{- with .Values.pod.command.cmd }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pod.command.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.pod.resources | nindent 12 }}
          {{- with .Values.pod.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.pod.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
