name: Lint and Test Charts

on:
  pull_request:
    paths:
      - 'stable/**'

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run chart-testing (lint)
        uses: helm/chart-testing-action@main
        with:
          command: lint
          config: .github/ct.yml

  kubeconform-chart:
    runs-on: ubuntu-latest
    needs:
      - lint-chart
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run kubeconform
        uses: nlamirault/helm-kubeconform-action@v0.1.0
        with:
          charts: ./stable

  install-chart:
    name: install-chart
    runs-on: ubuntu-latest
    needs:
      - lint-chart
      - kubeconform-chart
    strategy:
      matrix:
        k8s:
          - v1.26.14
          - v1.27.11
          - v1.28.7
          - v1.29.2
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@main
        with:
          node_image: kindest/node:${{ matrix.k8s }}
      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@main
        with:
          command: install
          config: .github/ct.yml
